Some calculations on nutriments

In [1]:
import pandas as pd
import numpy as np

In [31]:
# Globals

aa_columns = [
    "ILE Isoleucin [g/100g]",
    "LEU Leucin [g/100g]",
    "LYS Lysin [g/100g]",
    "MET Methionin [g/100g]",
    "PHE Phenylalanin [g/100g]",
    "THR Threonin [g/100g]",
    "TRP Tryptophan [g/100g]",
    "VAL Valin [g/100g]",
    "HIS Histidin [g/100g]",
    "CYSTE Cystein [g/100g]"
  ]

In [30]:
# Provision of further data

# Amino acid reference for a human(mg/g Protein), Source: ChatGPT (->WHO?)
aa_ref = {
  "Isoleucin": 30,
  "Leucin": 59,
  "Lysin": 45,
  "Methionin + Cystein": 22,
  "Phenylalanin + Tyrosin": 38,
  "Threonin": 23,
  "Tryptophan": 6,
  "Valin": 39,
  "Histidin": 15,
}

score_cols = [f"{k} score" for k in aa_ref.keys()]

In [3]:
df = pd.read_excel("BLS_4_0_Daten_2025_DE.xlsx", sheet_name=0)

df.head()

,BLS Code,Lebensmittelbezeichnung,Food name,ENERCJ Energie (Kilojoule) [kJ/100g],ENERCJ Datenherkunft,ENERCJ Referenz,ENERCC Energie (Kilokalorien) [kcal/100g],ENERCC Datenherkunft,ENERCC Referenz,WATER Wasser [g/100g],...,TYR Tyrosin [g/100g],TYR Datenherkunft,TYR Referenz,VAL Valin [g/100g],VAL Datenherkunft,VAL Referenz,"NT Stickstoff, gesamt [g/100g]",NT Datenherkunft,NT Referenz,Hinweis
0,C131000,"Hafer ganzes Korn, roh","Oat whole grain, raw",1443,Formelberechnung,-,343,Formelberechnung,-,11.45,...,0.424,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.6425,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",1.724,Aggregation,"Converted value from: Biel, W., et al.; Chemic...",NaN
1,C133000,Hafer Flocken,Oat flakes,1465,Formelberechnung,-,348,Formelberechnung,-,10.07,...,0.57,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.81,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",2.115,Analyse,-,NaN
2,C141000,"Gerste ganzes Korn, roh","Barley whole grain, raw",1403,Formelberechnung,-,332,Formelberechnung,-,12.7,...,0.341,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.5965,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",1.72,Literatur,Converted value from: Koivistoinen P; Mineral ...,NaN
3,C243000,Gerste Mehl,Barley flour,1434,Formelberechnung,-,340,Formelberechnung,-,6.06,...,0.301,Nährstoffdatenbank,"US Department of Agriculture, Agricultural Res...",0.515,Nährstoffdatenbank,"US Department of Agriculture, Agricultural Res...",1.6,Aggregation,"U.S. Department of Agriculture (USDA), Agricul...",NaN
4,C341000,Mais roh,Maize raw,1418,Formelberechnung,-,336,Formelberechnung,-,11.192,...,0.3935,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.4535,Nährstoffdatenbank,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",1.385,Nährstoffdatenbank,"Converted value from: Kirchhoff, E; Souci - Fa...",NaN

In [67]:
def get_instances_by_name(name):
  return df[df['Lebensmittelbezeichnung'].str.contains(name, case=False, na=False)]

# This function has to be adopted when nutriments occur that include non veggie products
# However, it may be beneficial to exclude some words for example "bolognese" because they could appear next to "veggie" or similar in one instance
def get_veggie_only(df):
  non_veggie_keywords = ("Aal", "Barsch", "Brasse", "Fisch", "Fleisch", "Flunder", "Garnele", "Gulasch", "Hammel", "Hecht", "Hummer", "Kasseler", "Karpfen", "Krabbe", "Krebs", "Kuh", "Lachs", "Lamm", "Languste", "Leber", "Leng", "Meeräsche", "Mortadella", "Ochse", "pork", "Rind", "Rotzunge", "Salami", "Sardelle", "Sardine", "Scampi", "Schaf", "Schinken", "Schleie", "Schnecke", "Scholle", "Schwein", "Seeteufel", "Seezunge", "Sprotte", "Steinbutt", "Wels", "Wurst", "Würst", "Zander")
  keyword_str = "|".join(non_veggie_keywords)
  return df[~df['Lebensmittelbezeichnung'].str.contains(keyword_str, case=False, na=False)]

In [15]:
def get_aa_profile(name):
    products = get_instances_by_name(name)
    return products[["Lebensmittelbezeichnung", "PROT625 Protein (Nx6,25) [g/100g]"] + aa_columns]

In [33]:
def compute_aa_score(row):
  protein = row["PROT625 Protein (Nx6,25) [g/100g]"]

  if protein == 0 or pd.isna(protein):
      return (np.nan) * 9    # ALWAYS two values

  unit_convert_divisor = protein / 1000 # The value needs to be converted into mg per g Protein
  
  scores = {
        "Isoleucin": row["ILE Isoleucin [g/100g]"] / unit_convert_divisor / aa_ref["Isoleucin"],
        "Leucin": row["LEU Leucin [g/100g]"] / unit_convert_divisor / aa_ref["Leucin"],
        "Lysin": row["LYS Lysin [g/100g]"] / unit_convert_divisor / aa_ref["Lysin"],
        "Methionin + Cystein": row["MET Methionin [g/100g]"] / unit_convert_divisor / aa_ref["Methionin + Cystein"],
        "Phenylalanin + Tyrosin": row["PHE Phenylalanin [g/100g]"] / unit_convert_divisor / aa_ref["Phenylalanin + Tyrosin"],
        "Threonin": row["THR Threonin [g/100g]"] / unit_convert_divisor / aa_ref["Threonin"],
        "Tryptophan": row["TRP Tryptophan [g/100g]"] / unit_convert_divisor / aa_ref["Tryptophan"],
        "Valin": row["VAL Valin [g/100g]"] / unit_convert_divisor / aa_ref["Valin"],
        "Histidin": row["HIS Histidin [g/100g]"] / unit_convert_divisor / aa_ref["Histidin"],
  }


  aa_name, min_score = min(scores.items(), key=lambda x: x[1])
  return scores["Isoleucin"], scores["Leucin"], scores["Lysin"], scores["Methionin + Cystein"], scores["Phenylalanin + Tyrosin"], scores["Threonin"], scores["Tryptophan"], scores["Valin"], scores["Histidin"]
  


# The function returns the approximated biological values for all instances that contains the given name as substring
def get_aa_scores(name):
  aa_columns = [
    "PROT625 Protein (Nx6,25) [g/100g]",
    "ILE Isoleucin [g/100g]",
    "LEU Leucin [g/100g]",
    "LYS Lysin [g/100g]",
    "MET Methionin [g/100g]",
    "PHE Phenylalanin [g/100g]",
    "THR Threonin [g/100g]",
    "TRP Tryptophan [g/100g]",
    "VAL Valin [g/100g]",
    "HIS Histidin [g/100g]",
    "CYSTE Cystein [g/100g]"
  ]
  products = get_instances_by_name(name)[[
    "Lebensmittelbezeichnung"] + aa_columns]

  if products.empty:
    print("No products found!")
    products["Biologische Wertigkeit"] = np.nan
    products["Limitierende Aminosäure"] = None
    return products[[
        "Lebensmittelbezeichnung",
        "Biologische Wertigkeit",
        "Limitierende Aminosäure"
    ]]

  products[aa_columns] = products[aa_columns].apply(
    pd.to_numeric,
    errors="coerce"
  )
  score_cols = [f"{k} score" for k in aa_ref.keys()]
  products[score_cols] = (
    products.apply(
        compute_aa_score,
        axis=1,
        result_type="expand"
    )
  )

  return products[["Lebensmittelbezeichnung", "PROT625 Protein (Nx6,25) [g/100g]"] + score_cols]

get_veggie_only(get_aa_scores("")).sort_values('Lysin score', ascending=False).head(10)

,Lebensmittelbezeichnung,"PROT625 Protein (Nx6,25) [g/100g]",Isoleucin score,Leucin score,Lysin score,Methionin + Cystein score,Phenylalanin + Tyrosin score,Threonin score,Tryptophan score,Valin score,Histidin score
453,"Rind Blut, roh",17.800,0.749064,2.666159,4.082397,1.991828,2.128918,3.126527,NaN,3.068280,7.191011
4475,"Hummer gekocht, gebraten ohne Fett (Pfanne)",17.267,1.654408,1.759013,2.782443,1.571574,1.107985,2.324112,1.254802,1.290441,1.467153
4769,"Hummer gekocht, gegrillt",21.534,1.654748,1.759142,2.782164,1.572566,1.108406,2.323929,1.253831,1.290744,1.467447
3695,Hummer gekocht,14.722,1.655119,1.759157,2.781929,1.571550,1.108259,2.324235,1.256623,1.290586,1.467192
5771,"Hummer tiefgefroren, gekocht",14.722,1.655119,1.759157,2.781929,1.571550,1.108259,2.324235,1.256623,1.290586,1.467192
5569,"Hummer tiefgefroren, gebraten ohne Fett (Pfanne)",19.365,1.655908,1.759246,2.781651,1.572659,1.108892,2.323780,1.256563,1.289665,1.466563
5228,"Hummer tiefgefroren, gegrillt",23.257,1.656849,1.758537,2.781480,1.571374,1.108891,2.323751,1.261269,1.289934,1.467658
2515,Hummer tiefgefroren,15.900,1.656184,1.758874,2.781272,1.572327,1.108904,2.324310,1.257862,1.290114,1.467505
47,Hummer roh,15.900,1.656184,1.758874,2.781272,1.572327,1.108904,2.324310,1.257862,1.290114,1.467505
6612,"Hummer gegart, in Currysauce von heller/weißer...",10.070,1.655081,1.733627,2.714333,1.534712,1.097580,2.288330,1.257862,1.273139,1.449851

In [37]:
def combine_products(product_names):
  if len(product_names) == 0:
    print("No names specified")
    return
  product_score_matrix = []
  for product in product_names:
    aa_score = get_aa_scores(product[0])
    aa_score[list(score_cols)] *= product[1]
    product_score_matrix.append(aa_score)
  n = min(len(df) for df in product_score_matrix)
  combination = product_score_matrix[0]
  for i in range(1, len(product_score_matrix)):
    combination[list(score_cols)] = combination[list(score_cols)].iloc[:n].values + product_score_matrix[i][score_cols].iloc[:n].values
    combination["Lebensmittelbezeichnung"] = combination["Lebensmittelbezeichnung"].iloc[:n].values + " + " + product_score_matrix[i]["Lebensmittelbezeichnung"].iloc[:n].values
  #combination[list(score_cols)] /= len(product_score_matrix)
  return combination

combine_products([("Weizen Mehl, Type 405", 0.45), ("Gouda ", 0.55)])

,Lebensmittelbezeichnung,"PROT625 Protein (Nx6,25) [g/100g]",Isoleucin score,Leucin score,Lysin score,Methionin + Cystein score,Phenylalanin + Tyrosin score,Threonin score,Tryptophan score,Valin score,Histidin score
208,"Weizen Mehl, Type 405 + Gouda 48 % Fett i. Tr.",10.46,1.509676,1.483342,1.276438,1.030673,1.395437,1.478953,2.053368,1.428313,1.850874

In [7]:
all_veggie_products = get_veggie_only(get_aa_scores(""))
all_veggie_products["BW"] = all_veggie_products[score_cols].min(axis=1)
#get_aa_scores("Vollmilch ")
#combine_products(["Vollmilch frisch, 3,5 % Fett, pasteurisiert", "Weizen Mehl, Type 405"])
all_veggie_products[["Lebensmittelbezeichnung", "BW", "PROT625 Protein (Nx6,25) [g/100g]"]].sort_values("BW", ascending=False).head(50)

,Lebensmittelbezeichnung,BW,"PROT625 Protein (Nx6,25) [g/100g]"
371,"Malzgetränk, alkoholfrei",8.771930,0.380
839,Süßrahmbutter,1.723643,0.590
6871,Pastete im Brotteig gebacken,1.649008,19.530
5695,"Sahnejoghurt mind. 10 % Fett, mit Fruchtzubere...",1.623377,2.800
2699,"Hühnerei Eiklar, gekocht",1.616162,9.900
233,"Hühnerei Eiklar, roh",1.616162,9.900
3495,"Hühnerei Eiklar, pochiert",1.616043,10.100
3723,"Hühnerei Eiklar, gebraten ohne Fett (Pfanne)",1.615612,10.900
3256,"Hühnerei Eiklar, gebacken",1.615240,11.700
1798,"Sahnejoghurt mind. 10 % Fett, mit Vanillezuber...",1.614435,2.700
5358,"Schneeklößchen gesüßt, Suppeneinlage",1.607815,7.200
2063,Baiser,1.600753,6.300
5130,"Brätblock dunkel, zur Rouladenherstellung",1.598002,13.350
1442,"Sahnejoghurt mind. 10 % Fett, mit Schokoladenz...",1.567398,2.900
6018,Baiser-Eistorte,1.560191,3.900
6905,Knacker mit Senf,1.549875,19.770
356,"Schnittkäse aus Ziegenmilch, mind. 50 % Fett i...",1.546783,19.160
3902,Debrecziner roh,1.531644,23.320
7056,Mosaikroulade,1.526020,12.640
2522,Landjäger,1.521467,22.330
5216,Kabanossi/Peperoni,1.518932,21.270
6020,Krakauer/Kochpolnische,1.514696,15.800
7086,Knacker mit Kartoffelsalat und Senf,1.511129,8.300
230,Hühnerei Pulver,1.510297,46.000
6394,"Krakauer/Kochpolnische, Konserve",1.509918,15.850
7017,Trüffelmosaikpastete,1.507547,14.100
5993,Cabanossi gebrüht,1.501655,15.260
746,Romadur mind. 40 % Fett i. Tr.,1.492367,23.100
2046,Salzburger Nockerl gebacken,1.491228,8.400
5150,"Brätblock mittel, zur Rouladenherstellung",1.491161,13.010
355,Limburger mind. 40 % Fett i. Tr.,1.490980,21.180
6304,Käsewiener gargezogen,1.486102,12.500
4416,Käsewiener,1.484693,12.900
5164,Erdbeerschnee,1.483051,2.400
4423,"Schaumomelett gesüßt, gebraten, mit Zitronensa...",1.469712,10.600
581,Putenei roh,1.466490,13.700
1429,Putenei gekocht,1.466490,13.700
4182,Weinschaumsauce/Weinchaudeau,1.465149,3.700
5391,Krakauer roh,1.458847,23.270
2845,Omelett gebraten mit Käse,1.457912,13.200
1019,Entenei roh,1.456568,12.800
2505,Entenei gekocht,1.456568,12.800
2321,Wachtelei gekocht,1.456276,13.175
580,Wachtelei roh,1.456276,13.175
3147,Wachtelei gebraten ohne Fett (Pfanne),1.455755,14.507
5149,Schaumeierkuchen (Omelette souffle) gebraten,1.451613,9.300
2906,Gänseei gekocht,1.451043,13.900
579,Gänseei roh,1.451043,13.900
7069,"Eier gekocht, mit Remouladensauce, gestreckt m...",1.450288,9.700
6914,Eier russisch,1.443001,12.600

In [90]:
combine_products([("seitan", 0), ("Vollmilch", 1)])

,Lebensmittelbezeichnung,"PROT625 Protein (Nx6,25) [g/100g]",Isoleucin score,Leucin score,Lysin score,Methionin + Cystein score,Phenylalanin + Tyrosin score,Threonin score,Tryptophan score,Valin score,Histidin score
1422,Fleischersatz glutenhaltig (Seitan) + Vollmilc...,28.4,2.173884,1.695808,1.764311,1.141565,1.300493,2.042969,2.362917,1.796856,1.782315